name: Continuous Deployment
on:
  push:
    branches:
      - master
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build
  PublishNugetPackage:
    name: Publish PigTracks.Sensors NuGet Package
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build --configuration Release
      - name: Push
        run: dotnet nuget push "PigTracks.Sensors/bin/Release/PigTracks.Sensors.*.nupkg" --source https://nuget.pkg.github.com/PigTracks/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
